# Don't run integration tests in Travis.
# We don't yet have a solution for this, perhaps in the future we can have a
# cloud VM firewall constantly accessible.
env:
  - NO_TEST=true

# Golang environment
language: go
dist: xenial

branches:
  only:
  - master
  - /^v.*/

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libcap-dev
  - sudo apt-get -y install libpcap-dev

after_success:
  - go get github.com/inconshreveable/mousetrap
  - GOOS=windows GOARCH=amd64 go build -o ./panutil.exe
  - GOOS=darwin GOARCH=amd64 go build -o ./panutil-mac
  - GOOS=linux GOARCH=amd64 go build -o ./panutil
  - ls -l

deploy:
  provider: releases
  api_key: $api_token
  file:
    - "panutil.exe"
    - "panutil"
    - "panutil-mac"

  skip_cleanup: true
  on:
    tags: true