# Don't run integration tests in Travis.
# We don't yet have a solution for this, perhaps in the future we can have a
# cloud VM firewall constantly accessible.
env:
  - NO_TEST=true

# Golang environment
language: go
dist: xenial

branches:
  only:
  - master
  - /^v.*/

after_success:
  - go get github.com/inconshreveable/mousetrap
  - GOOS=windows GOARCH=amd64 go build -o ./panutil.exe
  - ls -l

deploy:
  provider: releases
  api_key: $api_token
  files:
    - "panutil.exe"
  skip_cleanup: true
  on:
    tags: true