package clientapi

/*
This file contains all the definitions for the Panutil API

The API uses the following convention for status messages:
	0: Status OK/Complete
	1: Firewall based error has occured (invalid request, malformed xml, etc)
	99: Panutil based error has occured (system unavailable, crash, etc.)

A simple key is generated by Panutil when the client succesfully logs onto a firewall.
This key is then required for all command requests. The key is only relevant for a single run of panutil.
This prevents users on a multi-user system from sending requests via someone elses panutil session.
*/

// Status message, used for communicating information about the panutil runtime
type StatusMessage struct {
	Status  int
	Message string
}

// Login message and repsonse
type LoginRequest struct {
	Hostname string
	Username string
	Password string
}
type LoginResponse struct {
	ApiKey string
	Status int
}

// Command request.
type Command struct {
	ApiKey  string
	Command string
	Args    []string
}
